### ISSUE TITLE
Can't compile when using a class enhanced with Lombok

### ISSUE THREAD

**Issue by VictorAlbertos** [tbroyer/gradle-apt-plugin#10]
Hi!

Thanks for this amazing plugin, thanks to it I can use Dagger 2 in a pure java module :) 

But I've found a problem using it with [Lombok]
(https://projectlombok.org). 

I have declared this class:

@AllArgsConstructor(access = AccessLevel.PROTECTED)
@Data
public class UserDemoEntity {
    private final int id;
    private final String login;
}

But when I try to compile the module I get this error:

error: variable id not initialized in the default constructor
error: variable login not initialized in the default constructor

If I try to use the generated setter by Lombok for the attributes in any class, I get this error too. 
Error: cannot find symbol method getId()

It seems like the [plugin](https://github.com/mplushnikov/lombok-intellij-plugin) I’ve installed for Intellj in order to support Lombok annotations crashes when using this plugin. 

But the "structure window" of the Ide still shows the autogenerated setter/getters etc

<img width="741" alt="screen shot 2015-11-13 at 00 02 50" src="https://cloud.githubusercontent.com/assets/2614726/11133988/c84005e2-8999-11e5-922b-7b6413129c3e.png">

I'm using Android Studio by the way. 

Thanks!

**Comment by tbroyer** [comment]
As far as IntelliJ is concerned, the gradle-apt-plugin only configures your `apt` and `compileOnly` (resp. for tests) as compile dependencies in IntelliJ so that you can simply enable annotation processing in IntelliJ and annotations are processed from within the IDE. So you should try creating a project that does not use the `gradle-apt-plugin` and simply puts your Dagger dependencies at `compile` scope, and see if you reproduce the issue.

Lombok is a clever hack, but an hideous hack anyway, and I strongly believe no sane person should be using Lombok. There **are** non-hackish alternatives, even if they're not always automated at the same level (at a minimum, use delombok to generate plain Java sources so that you don't need to inject Lombok's hacks everywhere in your toolchain).
In any case, I believe the issue is with the lombok-intellij-plugin, not the gradle-apt-plugin or anything else.

**Comment by VictorAlbertos** [comment]
Hi! 

I've configured my project as you suggested:

"So you should try creating a project that does not use the gradle-apt-plugin and simply puts your Dagger dependencies at compile scope, and see if you reproduce the issue".

And when I run the task compileJava, I don't get any error. But as soon as I "use cradle-apt-plugin", I get the error already commented.

**Comment by tbroyer** [comment]
OK, let me try to reproduce then. How's Lombok configured? Maybe you can share snippets of your `gradle.build`?

**Comment by tbroyer** [comment]
Note that I still believe the bug is **not** in gradle-apt-plugin. Also, is the error only in IntelliJ/Android Studio or (also?) when building with Gradle? (it's not very clear from your reports)

**Comment by VictorAlbertos** [comment]
The error happens too when building with Gradle.

Top level build project
https://gist.github.com/VictorAlbertos/8b57b5240babc8863bb2

Build file for the specific module called "domain". 
https://gist.github.com/VictorAlbertos/1e14d6047f511ebba508#file-build-module-gradle

Here some screenshots of the output generated when trying to run the task compile java for the domain module:

<img width="1242" alt="screen shot 2015-11-13 at 14 30 01" src="https://cloud.githubusercontent.com/assets/2614726/11147007/4c84788c-8a13-11e5-9041-5e96ffe23317.png">

<img width="1241" alt="screen shot 2015-11-13 at 14 30 32" src="https://cloud.githubusercontent.com/assets/2614726/11147010/510c1734-8a13-11e5-8a4d-431f3d8327c8.png">

And the class enhanced with lombok:

<img width="657" alt="screen shot 2015-11-13 at 14 30 39" src="https://cloud.githubusercontent.com/assets/2614726/11147016/5de185f2-8a13-11e5-889e-f437e98280ac.png">

**Comment by tbroyer** [comment]
Because I'll never install an IntelliJ plugin for Lombok, I tested in pure Gradle, in three flavors:

First with everything in the `compile` scope:
```groovy
apply plugin: 'java'

repositories {
  mavenCentral()
}
dependencies {
  compile 'com.google.dagger:dagger-compiler:2.0.2'
  compile 'org.projectlombok:lombok:1.16.6'
}
compileJava {
  outputs.dir 'gen/'
  doFirst { mkdir('gen/') }
  options.compilerArgs += [ '-s', 'gen/' ]
}
```

Then with an `apt` configuration and using the `-processorpath` (more or less what the gradle-apt-plugin does):
```groovy
apply plugin: 'java'

repositories {
  mavenCentral()
}
configurations {
  apt
}
dependencies {
  compile 'com.google.dagger:dagger:2.0.2'
  apt 'com.google.dagger:dagger-compiler:2.0.2'
  compile 'org.projectlombok:lombok:1.16.6'
  apt 'org.projectlombok:lombok:1.16.6'
}
compileJava {
  inputs.files configurations.apt
  outputs.dir 'gen/'
  options.compilerArgs += [ '-s', 'gen/', '-processorpath', configurations.apt.asPath ]
  doFirst {
    mkdir('gen/')
  }
}
```
And finally with the gradle-apt-plugin:
```groovy
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "net.ltgt.gradle:gradle-apt-plugin:0.4"
  }
}

apply plugin: "net.ltgt.apt"
apply plugin: 'java'

repositories {
  mavenCentral()
}
dependencies {
  compileOnly 'com.google.dagger:dagger:2.0.2'
  apt 'com.google.dagger:dagger-compiler:2.0.2'
  compileOnly 'org.projectlombok:lombok:1.16.6'
  apt 'org.projectlombok:lombok:1.16.6'
}
```

In all cases this compiles without error. As source files, I used your class from above, a dummy Dagger `@Module` class to trigger the Dagger annotation processor (the `options.compilerArgs` above are used to get the generated `Module_…Factory` class and thus verify the annotation processor is correctly triggered), and a `Main` class the instantiates your class and calls its getters (i.e. makes use of Lombok-generated constructor and getters).

**Comment by VictorAlbertos** [comment]
Thanks for the support!

The problem was fixed adding this line to my build gradle module domain (I saw it in your snippet):

apt 'org.projectlombok:lombok:1.16.6'

But if I don't use your plugin the task compileJava works fine. I don't know why this happens, but my knowledge of gradle is pretty limited.

**Comment by tbroyer** [comment]
gradle-apt-plugin (and the android-apt plugin I believe, see https://projectlombok.org/setup/android.html) puts the `apt` dependencies in the _processor path_ of `javac` (see second try above) so there's a clear separation between the dependencies your code can rely on and the ones depended on by the annotation processors.
See https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html for more information about `-processorpath`.
