### ISSUE TITLE
Annotation processor does not run in Eclipse multi-project

### ISSUE THREAD

**Issue by traggatt** [tbroyer/gradle-apt-plugin#17]
I have a project where I'm trying to use Dagger 2 to generate DI sources in an Eclipse multi-project. I'm finding that the Dagger sources are not generated for my sub-project when I import the build into Eclipse.

I've replicated the issue in this standalone git repo: https://github.com/traggatt/AptTest

Notes:
- When imported into Eclipse, I see the following Annotation Processor settings for sub-project `aptProject`:
![screen shot 2016-02-17 at 09 47 49](https://cloud.githubusercontent.com/assets/4661772/13105546/a11596c2-d55b-11e5-9933-9805172cf175.png)
- The build works from the command line. Since the `Runner` depends on Dagger generated class, `DaggerTestComponent`, the source code generation is clearly working ok in this context. (Indeed I can see the generated source code here: `aptProject/build/generated/source/apt/main/aptProject`.)

Before I converted my project into multi-project form, the Dagger sources generated into `.apt_generated`.

**Comment by traggatt** [comment]
Just realised I forgot to mention, I'm using Eclipse Mars with its built-in gradle support.

**Comment by tbroyer** [comment]
Hmm, I haven't tried Buildship but I suppose it's a similar issue as the Gradle integration in IntelliJ: Eclipse configuration to automatically enable annotation processing is done by tasks set as dependencies of the `eclipse` task, but I don't think Buildship actually runs the `eclipse` task.

You can manually run the `eclipseJdtApt` and `eclipseFactorypath` tasks to generate the appropriate configuration files in `.settings/`, but then you might also have to manually enable annotation processing in Eclipse.

**Comment by tbroyer** [comment]
Just tried with your project:

 1. cloned it
 2. Imported it in Eclipse Mars
 3. Ran `./gradlew eclipseJdtApt eclipseFactorypath` (you can also run the tasks from the _Gradle Tasks_ view in Eclipse, after you set it up to _Show All Tasks_)
 4. Refreshed the project: configuration of annotation processing was OK (enabled, output in `.apt_generated`, factorypath properly populated)
 5. Rebuilt it (strangely, cleaning the project wasn't enough; disabling and re-enabling annotation processing worked though; didn't try closing/reopening Eclipse; didn't look further given it was working)

I also tried running the two tasks before importing the projects and it worked too; but again I had to force Eclipse to rebuild the project (first time fails, presumably because `.apt_generated` doesn't exist).
For as far as I can remember, I always had those kind of issues with Eclipse annotation processing (one of the reasons I personally switched to IntelliJ; YMMV)

**Comment by vogella** [comment]
> disabling and re-enabling annotation processing worked though; didn't try closing/reopening Eclipse

Reported this to JDT https://bugs.eclipse.org/bugs/show_bug.cgi?id=514055

**Comment by thekalinga** [comment]
@vogella Is annotation processing working for you? or you also moved away from eclipse?

**Comment by thekalinga** [comment]
I opened another issue this time with mapstruct. Mine does not work even after turning annotation processors on or off

https://github.com/spring-projects/spring-ide/issues/273

**Comment by thekalinga** [comment]
@vogella Thanks. I'll check & see whats the difference between yours and mine
