### ISSUE TITLE
Google App Engine gradle plugin: functionalTest source sets?

### ISSUE THREAD

**Issue by renaudcerrato** [tbroyer/gradle-apt-plugin#18]
Hi there!

I was successfully using your apt plugin on a GAE project for weeks ([gradle plugin](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin)), until I started to wrote functional tests:

```
> ./gradlew appengineFunctionalTest
....
/home/renaud/Workspace/appengine/backend/src/functionalTest/java/backend/test/InjectingTest.java:5: error: cannot find symbol
import backend.test.dagger.DaggerFunctionalTestComponent;
                        ^
  symbol:   class DaggerFunctionalTestComponent
  location: package backend.test.dagger
...
```

IMO, the plugin should run the annotation processor on any relevant path, not only `main` and `test` ?

**Comment by tbroyer** [comment]
I'll try to update the plugin to act on every `sourceSet`, but there'd still be an open question that would require plugin-dependent (or manual) configuration: how to configure the IDEs? I mean, for Eclipse it's relatively easy as there's only one build path, but for IntelliJ IDEA, should the `sourceSet` be added as a _main_ or _test_?

**Comment by renaudcerrato** [comment]
I told my Intellij IDEA to consider `functionalTest` as `test`, doing so I'm able to run them like any other tests (but the generated code is placed under `test` too, I had to be careful about collisions).

**Comment by tbroyer** [comment]
> I told my Intellij IDEA to consider `functionalTest` as `test`,

Doesn't the gradle-appengine-plugin do it already?

> doing so I'm able to run them like any other tests (but the generated code is placed under `test` too, I had to be careful about collisions).

Ah right, that's another problem yes; annotation processing in IntelliJ should no longer use the same output paths as the Gradle build then. Maybe I could expose some API to make it easier to configure IntelliJ (and Eclipse) for other source sets…

**Comment by renaudcerrato** [comment]
> Doesn't the gradle-appengine-plugin do it already?

I'm an IDEA noob but, from what I've experimented, it seems that Intellij IDEA has absolutely no idea about that `appengineFunctionalTest` task and related source set. By manually declaring them as "test sources", I'm able to run them as regular unit tests (but the development server is NOT started in the background unlike what the gradle task is doing).

I struggled a lot to have a semi-working IDE environment: even when I used your plugin and properly configured the annotation processors settings, IDEA didn't see the generated classes. I had to manually include the apt source folder to the module settings.

**Comment by tbroyer** [comment]
I had a look at it and it should be easy to configure your environment:

```gradle
sourceSets.functionalTest.compileClasspath = sourceSets.main.output + configurations.functionalTestCompileOnly

apply plugin: 'idea'
idea {
  module {
    testSourceDirs += "$project.buildDir/generated/source/apt/functionalTest"
    generatedSourceDirs += "$project.buildDir/generated/source/apt/functionalTest"
    scopes.TEST.plus += [ project.configurations.functionalTestCompileOnly, project.configurations.functionalTestApt ]
  }
}
```

I hesitate to add built-in support for the AppEngine plugin because it would mean potentially adding support for many more other plugins in the future.

Note that the `functionalTestCompileOnly` configuration will be _native_ in Gradle 2.12, so assuming Google update their plugin for Gradle 2.12, the first line above will no longer be necessary, and you'll only be left with configuring IDEA, which is only a few lines worth.
And I'm working at integrating as much as possible of this plugin into Gradle proper.

Re. the `appengineFunctionalTest` **task**, you can run it from IDEA like any other Gradle task; but that's an AppEngine / gradle-appengine-plugin issue that I'll let you ask on StackOverflow or their issue tracker (or any other channel; I don't use AppEngine…).
