### ISSUE TITLE
Incremental build leaves removed AutoValue classes in generated source and might lead to subsequent compilation errors

### ISSUE THREAD

**Issue by ias-dt** [tbroyer/gradle-apt-plugin#29]
use case with AutoValue, annotation processing and incremental build:
- we have an AutoValue type and already the generated source for this type
- then we remove the AutoValue type, but the generated source of this type still remains
- this might even lead to subsequent compilation errors

we therefore would like to propose the following:
- introduce a new option cleanGeneratedSourceDir (default false to retain current behavior)
- if true, clean the generatedSourceDir in the doFirst of the compile task

this way, we don't have any orphaned generated source lying around...
and once https://issues.gradle.org/browse/GRADLE-3259 is fixed, there might even be a better solution for this issue

**Comment by tbroyer** [comment]
Incremental compilation is really hard when annotation processors are being used, because the build tools has to track the dependencies that lead to generate a given file (class or not BTW). Only JavaC really knows about those dependencies, because annotation processors tell it about them (if coded properly) during generation: https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/Filer.html
Without that insight knowledge, one can possibly infer the dependencies from interactions of JavaC with the filesystem (AFAIK, this was what Pants did at some point), but then that requires using in-process JavaC (i;e. not forked), **and** hooking into it.

That goes way beyond the scope of this plugin.

So, until Gradle properly supports annotation processors with incremental compilation out of the box (managing both generated classes/resources and generated source files), you won't be able to have it working.
