### ISSUE TITLE
Missing expected maven metadata? Always downloads even when in cache

### ISSUE THREAD

**Issue by novaterata** [tbroyer/gradle-apt-plugin#34]
Of all my gradle dependencies, this is the only one that always downloads even if it's in the cache. I'm also using     id 'com.github.ben-manes.versions' version '0.13.0' to check for updated dependencies, and this is the only library that cannot be checked. I'm assuming some expected metadata in the pom is missing.

**Comment by tbroyer** [comment]
Could net.ltgt.apt be the only plugin coming from plugins.gradle.org/m2? (without being also available through JCenter, as is the case for com.github.ben-manes.versions; because plugins.gradle.org/m2 will forward to JCenter if it doesn't host something by itself).
This plugin is published using plugins.gradle.org's own publishing plugin, and this one is known to not create a full Maven repository with metadata (`maven-metadata.xml` files, telling which is the latest version for a given artifact, nothing to do with POM content actually; which is also why com.github.ben-manes.versions cannot check for newer versions), probably because they expect you to pin a specific version of a plugin and not use version ranges or `latest.release` versions.

I'd suggest bringing this issue to Gradle: https://discuss.gradle.org, or possibly to @ben-manes as it might possibly be some interaction with his plugin.

**Comment by ben-manes** [comment]
The Gradle team has repeatedly ignored my requests to fix the maven-metadata.xml. Since the plugin delegates to Gradle to evaluate, it's breaking their ability to handle ranges. Asking on the forum is the best advice as maybe they'll decide to resolve it. Publishing to Jcenter directly seems to be the best strategy.

**Comment by novaterata** [comment]
Thanks, that makes sense. I already nagged then about it, but got nothing.
