### ISSUE TITLE
Confusion around failed build when using apt

### ISSUE THREAD

**Issue by tkruse** [tbroyer/gradle-apt-plugin#39]
Hi,

I noticed this problem when I tried using autovalue. The code below worked fine with autoValue added as CompileOnly Dependency (regardless of whether the net.ltgt.apt plugin was applied or not.

However, when I added an annotation processor as apt dependency (forgetting autoValue), like commenting out in the pasted example below, the project would not build anymore:
```
...
error: cannot find symbol
                return new AutoValue_Car
```

Adding auto_value as apt dependency as well fixed this. Not sure if that is the intended behavior, I found it mighty confusing. Even if this is intended behavior, it might be nice to provide somethin like maybe and AptAndCompileOnly dependency scope for all the libraries that bundle an annotation processor and annotations in the same jar.

To reproduce, using Gradle 3.3, Java 8, Ubuntu Linux
```groovy
// build.gradle:
plugins {
	id "net.ltgt.apt" version "0.9"
}

apply plugin: 'java'

repositories {
  jcenter()
}

dependencies {
//  apt 'org.immutables:value:2.4.2'    // using this as only apt dependency breaks auto-value
  compileOnly 'com.google.auto.value:auto-value:1.3'
// apt 'com.google.auto.value:auto-value:1.3'   // need this only when using any other apt

  compile 'com.google.code.findbugs:jsr305:2.0.3'
  compile 'com.google.guava:guava:19.0'
  
  testCompile 'junit:junit:4.11'
  testCompile 'org.mutabilitydetector:MutabilityDetector:0.9.2'
}
```
```java
// Java source
import com.google.auto.value.AutoValue;

@AutoValue
public abstract class Car {
	
	public abstract String model();
	public abstract int numWheels();
	
	public static Car create(String model) {
		return new AutoValue_Car(model, 4);
	}
}
```

**Comment by tbroyer** [comment]
This is indeed the intended behavior.

Actually, if you read the README closely, you'll find this:
> Note that up until version 0.7, if [the `apt` and `testApt`] configurations were empty, an empty processor path (`-processorpath :`) would be passed to `javac`; this was a breaking change compared to the normal behavior of Gradle, as it meant annotation processors wouldn't be looked up in the tasks' `classpath`. Starting with version 0.8, no `-processorpath` will be passed if the `<sourceSet>Apt` configuration is empty; this is to follow the [proposal to add first-class support for annotation processing to Gradle proper](https://github.com/gradle/gradle/blob/master/design-docs/java-annotation-processing.md)

So, with versions up to 0.7, your current configuration (with only `compileOnly` actually wouldn't have worked, and the behavior changed in 0.8. I suggest you read the [JavaC documentation](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html#sthref63) about how `-processorpath` is used and how annotation processors are looked up:
> The search path can be specified with the `-processorpath` option. If no path is specified, then the user class path is used.

This plugin does not intend to hide that as there'd inevitably be leaky abstractions.

So, without `apt` dependency, no `-processorpath` is passed to JavaC, which means the search path for annotation processors would be the compilation classpath (in Gradle terms, the [`JavaCompile` task's `classpath`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html#org.gradle.api.tasks.compile.JavaCompile:classpath); which itself defaults to being the [`main` source set's `compileClasspath`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html#org.gradle.api.tasks.SourceSet:compileClasspath), that's by default the `compileClasspath` configuration –the Gradle doc seems outdated–, that extends the `compileOnly` configuration, itself extending the `compile` configuration — phew!).

One thing you might not realize, is that the `<sourceSet>Apt` configurations are totally distinct from the `<sourceSet>CompileOnly` ones; which means you can have, say, Guava 21 in your `apt` (brought transitively by an annotation processor dependency) and Guava 19 in your `compile`, and they wouldn't conflict (by putting them in `compileOnly`, the Guava dependency would be "resolved" to Guava 21, so you'd compile against Guava 21, but would declare a "runtime dependency" of Guava 19 –from the `compile` configuration–, and that could lead to runtime errors because something you didn't expect to compile actually compiled –a Guava 21-only API– or other oddities)

**Comment by tbroyer** [comment]
BTW, if you want an `aptAndCompileOnly` configuration, you can use:
```groovy
configurations {
  aptAndCompileOnly
}
configurations.compileOnly.extends configurations.aptAndCompileOnly
configurations.apt.extends configurations.aptAndCompileOnly
```

But that's unnecessary complication IMO to just save you one line in your dependency declarations.

Also note that the example in the README explicitly adds AutoFactory to both `compileOnly` and `apt`. AutoValue works the same (for now at least: https://github.com/google/auto/issues/268)

**Comment by tkruse** [comment]
Thanks for the explanation. One thing I could imagine that might be useful is that if any apt-dependency is given, the gradle javaCompile task could make an info message about the path that is being used (given it is not the default classpath anymore). That would have helped me (I would have realized: "Oh, something non-default is going on, and the autoValue processor is not mentioned"). Not sure if your plugin would be involved in that logging, though.

**Comment by tbroyer** [comment]
You should have the exact arguments passed to JavaC in the `--debug` output (grep for "Compiler arguments" or `-classpath`); something like:

`16:32:06.243 [DEBUG] [org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler] Compiler arguments: -source 1.7 -target 1.7 -d /…/gradle-errorprone-plugin/build/classes/main -g -sourcepath /…/gradle-errorprone-plugin/build/tmp/compileJava/emptySourcePathRef -classpath /…/.gradle/caches/3.3/generated-gradle-jars/gradle-api-3.3.jar:/…/.gradle/wrapper/dists/gradle-3.3-bin/64bhckfm0iuu9gap9hg3r7ev2/gradle-3.3/lib/groovy-all-2.4.7.jar:/…/.gradle/wrapper/dists/gradle-3.3-bin/64bhckfm0iuu9gap9hg3r7ev2/gradle-3.3/lib/gradle-installation-beacon-3.3.jar /…/gradle-errorprone-plugin/src/main/java/net/ltgt/gradle/errorprone/ErrorProneCompiler.java /…/gradle-errorprone-plugin/src/main/java/net/ltgt/gradle/errorprone/ErrorProneBasePlugin.java /…/gradle-errorprone-plugin/src/main/java/net/ltgt/gradle/errorprone/ErrorProneToolChain.java /…/gradle-errorprone-plugin/src/main/java/net/ltgt/gradle/errorprone/ErrorPronePlugin.java -XDuseUnsharedTable=true`

(from my gradle-errorprone-plugin, that one does not use annotation processors)
