### ISSUE TITLE
Build error when using custom compile tasks

### ISSUE THREAD

**Issue by batousik** [tbroyer/gradle-apt-plugin#41]
Error:Cannot convert path to File. path='net.ltgt.gradle.apt.AptPlugin$_apply_closure1$_closure14@111eebf1' basedir='D:\git\project\android\app'

**Comment by tbroyer** [comment]
I need more information. A repro case maybe? or the `--debug` log?

**Comment by nghib** [comment]
I have same issue

Cannot convert path to File. path='net.ltgt.gradle.apt.AptPlugin$_apply_closure1$_closure14@1a30194b' basedir='/Users/nghib/spring/gradle-apt-bug-report'

I submit a repository for reference
https://github.com/nghib/gradle-apt-bug-report/blob/master/build.gradle

You can run ./gradlew compileJava to see the issue.

if I disable line #97 (mapstruct) in build.gradle, there is no error.

**Comment by tbroyer** [comment]
Thanks a lot for the repro case!

So, this happens when the task's `generatedSourcesDestinationDir` evaluates to `null`. If you set it to a non-null value (e.g. `generatedSourcesDestinationDir = destinationDir` in the `generateQueryDSL` task) then compilation passes. This only happens for "custom" `JavaCompile` tasks like your `generateQueryDSL` task, as all tasks generated by source-sets are configured with a non-null value by convention.

Working on a fix.

**Comment by tbroyer** [comment]
Should be fixed by 0496be8ebf92634f51dacf283fb42d58eba81224; would you mind testing with the latest snapshot? (from JitPack; see the README)

**Comment by nghib** [comment]
Thanks @tbroyer for the quick fixes. It works for me for SNAPSHOT version on jitpack.io

**Comment by tbroyer** [comment]
FYI, I just released v0.10 (with better support for Gradle 3.4)
