### ISSUE TITLE
FYI: Annotation processing with Gradle 3.4.1 and "Use separate module per source set"

### ISSUE THREAD

**Issue by anuraaga** [tbroyer/gradle-apt-plugin#43]
Hello - I know in other issues you have mentioned that IntelliJ support is just best effort and your recommended configuration is to uncheck "use separate modules". With newer gradles, I've found that unchecking this causes other problems and that for future-proofness it's probably good to support it.

I dug though and came up with a configuration that seems to work with separate modules, and also uses gradle's built in apt support as of 3.4 - IntelliJ build (not delegate to gradle) works great with no user configuration at all. I'm just pasting it here in case it's useful information for you in a future version of this plugin. I'd be happy to switch back to the plugin :) This issue is just to document it, feel free to close right away.

To sum, I think the key changes are
- Modern gradle idea plugin seems to allow adding subdirectories of build/ without any exclusion weirdness
- Gradle's idea.module.scopes seems to be sort of broken. But using compileOnly is actually simpler and works perfectly - the processors are added as PROVIDED, but any dependencies that are also used by the project are added as COMPILED.
- Annotation processing output directories in the project are set to current directory '.'. I'm not sure why this works, but it does seem to have intellij put the files into the generated sources directory (maybe it finds the first generated sources directory and dumps into them).

All projects
```groovy
[sourceSets.main, sourceSets.test].each { sourceSet ->
            // HACK: Configurations usually use the same naming logic/scheme as for tasks
            def aptConfiguration = configurations.create(sourceSet.getTaskName('', 'apt'))
            // Makes sure IDEs can find the annotation processor on the compile classpath.
            // Since it's compileOnly, it doesn't affect the result.
            configurations.getByName(sourceSet.getTaskName('', 'compileOnly'))
                    .extendsFrom(aptConfiguration)

            def outputDir = "$buildDir/generated/source/apt/${sourceSet.name}"
            tasks.getByName(sourceSet.compileJavaTaskName) {
                project.mkdir(outputDir)
                options.annotationProcessorPath = aptConfiguration
                options.compilerArgs += ['-s', outputDir]
            }

            project.plugins.withType(IdeaPlugin) {
                project.idea.module {
                    if (sourceSet == sourceSets.main) {
                        sourceDirs += file(outputDir)
                    } else {
                        testSourceDirs += file(outputDir)
                    }
                    generatedSourceDirs += file(outputDir)
                }
            }
        }
}
```

Root project
```groovy
idea.project.ipr.withXml {
    def compilerConfiguration = it.node.component.find { it.@name == 'CompilerConfiguration' }
    compilerConfiguration.remove(compilerConfiguration.annotationProcessing)
    compilerConfiguration.append(new groovy.util.NodeBuilder().annotationProcessing() {
        profile(name: 'Default', enabled: true, default: true) {
            outputRelativeToContentRoot(value: true)
            processorPath(useClasspath: true)
            sourceOutputDir(name: '.')
            sourceTestOutputDir(name: '.')
        }
    })
}
```

**Comment by tbroyer** [comment]
> `// Since it's compileOnly, it doesn't affect the result.`

This is unfortunately wrong: dependencies from the `apt` configuration will _leak_ into the compilation classpath, which changes the resolution rules and might break the build (`apt` brings newer dependency with breaking change so code no longer compiles) or break at runtime (`apt` brings newer dependency with new API or breaking change, and you mistakenly code against it; compilation is OK but the older dependency is used at runtime; this should break tests too, but makes it difficult –more than necessary– to pinpoint the actual issue).

Those issues are the main reason for using a processor path separate from the compilation classpath (other reason is to avoid annotation processors from compilation classpath "leaking" into the processor path; this could also be solved in most cases by explicitly listing the processors to run, but not always; only other reason would be feeding custom checks to the Error Prone compiler); otherwise you'd just put your annotation processors into `compileOnly`.

Thanks for the suggestion though.

**Comment by anuraaga** [comment]
Thanks for the explanation - you're right the comment is wrong. But I wonder if it would still make sense as behavior guarded behind a enableIdeaProcessors config option. I agree that separating the annotation processor and compile classpath is ideal, but for convenience IntelliJ supports picking processors up from the compile classpath so I guess combining them is also sort of standard. It's why this plugin currently adds to scopes.COMPILE - I think the main difference with using compileOnly instead of scopes.COMPILE is that both ./gradlew and IntelliJ would have similar dependency hell behavior, while only touching scopes could cause confusing situations where the IntelliJ build fails but gradle succeeds.

FWIW, with this proposal, processors from the compilation classpath won't leak into the processor path since we're setting options.annotationProcessorPath = aptConfiguration - this disables gradle's default behavior of running processors found on the compile classpath. So the only problem seems to be the dependency hell possibility you described, but I guess that could already happen in an IntelliJ build, though not ./gradlew.

Anyways, I can see the issue with this proposal too, so it makes sense wanting to push the "delegate build to gradle" option instead :)

**Comment by tbroyer** [comment]
FWIW, the main reason this plugin puts annotation processor dependencies into IntelliJ's compile classpath is because the IDE integration won't use the `idea.project.ipr` configuration so manual configuration in IDEA has to remain easy. I really wish annotation processors are first-class citizens in Gradle so they could be expose through the tooling API and IDEs can simply pick them up and configure things cleanly (`.factorypath` in Eclipse, and processor dependencies in IDEA).

In the current state, I think the discrepancy is acceptable as long as the Gradle build is OK; the build is the source of truth, IDEs are _just_ tools to help you be productive (otherwise we'd all just use nano or the notebook).
