### ISSUE TITLE
Option to not change IntelliJ config

### ISSUE THREAD

**Issue by molexx** [tbroyer/gradle-apt-plugin#45]
When IntelliJ refreshes the build.gradle file this plugin updates the IntelliJ project's module's paths. Please could there be an option to not do this.

IntelliJ's internal build system and annotation compiler is working well for us, outputting to its own directory separate to gradle's build dir. When gradle's build directory is added in as well we get duplicate classes.

**Comment by tbroyer** [comment]
Hmm, and I suppose you need to `apply: 'idea'` for other reasons too? Sounds like a fair request…

Question: couldn't you either configure the sourcesets' `output.generatedSourceDir` to that “directory separate to gradle's build dir” or configure IntelliJ to use the `build/generated/source/apt/` folders?
BTW, which version of IntelliJ are you using? and how are you importing the project? (if a recent version of IntelliJ, are you using “create separate module per source set”?

BTW, the plugin doesn't do much, so maybe you could do things by hand rather than with the plugin:
```gradle
configurations {
  apt
  testApt
}
compileJava {
  // With Gradle 3.5+
  // options.annotationProcessorPath = configurations.apt
  // With all Gradle versions:
  inputs.files configurations.apt
  options.compilerArgs += [ '-processorpath', configurations.apt.asPath ]
}
compileTestJava {
  // Same remarks as above
  inputs.files configurations.testApt
  options.compilerArgs += [ '-processorpath', configurations.testApt.asPath ]
}
// Possibly add annotation processor dependencies  to IntelliJ
idea {
  module {
    // With Gradle 3.4:
    scopes.PROVIDED.plus += [ configurations.apt ]
    scopes.TEST.plus += [ configurations.testApt ]
    // With older Gradle versions:
    // scopes.COMPILE.plus += [ configurations.apt ]
    // scopes.TEST.plus += [ configurations.testApt ]
  }
}
```
(Gradle supports the `compileOnly` configurations since version 1.12, so I didn't include it here)

From my point of view, one shouldn't have to tweak IDE configurations to get things working, it should ideally work out of the box when importing the projects (and I just tested with 2017.1 and a small project, and even with "create separate module per source set" it seems to Just Work™, delegating the build to Gradle by default), and IDE configuration should ideally only differ from build configuration when it matters (such as Eclipse having a single generated sources output directory for both main and test classes); so I suppose you could maybe make your IntelliJ and Gradle configurations agree with each other regarding the generated sources output folders.

**Comment by molexx** [comment]
Thanks.

Changing properties/configs to have gradle's and intellij's processors writing to the same directory is something we'd like to avoid as we're often running both at the same time (running the test suite or app from gradle in a terminal window) and they either lock the files preventing clean or get upset when another process overwrites the classes in use causing version mismatches.

Currently on 2016.3.6, soon to be updating to 2017.1.

I'm not using "create separate module per source set". The project only has one module.

I don't want to delegate IntelliJ's build to gradle because it's slower, IntelliJ's 'build automatically' gives quick feedback without interrupting flow. It'll also interfere with the gradle that's running in a terminal window.

I agree about tweaking IDE configurations. I expect that what we're doing - wanting to keep IDE and gradle builds separate because we run both at the same time - isn't very common so I'd request that this be an option which defaults to 'please update my IntelliJ project configuration for me'.

I guess it might be useful for others who have their own reasons to change IntelliJ's paths.

**Comment by jaredsburrows** [comment]
@tbroyer Does your plugin allow "compile avoidance" https://blog.gradle.org/incremental-compiler-avoidance with annotation processors?

**Comment by tbroyer** [comment]
@jaredsburrows The plugin doesn't use `options.annotationProcessorPath` (yet), so I'll have to check whether Gradle only uses this property or also looks for `-processorpath` in arguments.

(I don't get why you hijacked this completely unrelated issue though)

**Comment by jaredsburrows** [comment]
@tbroyer Sorry. I was googling and found that helpful code snippet that was similar to the one provided in the link in my previous comment.
Do you want me to me this question to a separate issue/question?
When we can change your plugin to use `annotationProcessorPath`?
Once this happens, I'd love to test it out on Android projects.

**Comment by tbroyer** [comment]
@jaredsburrows Looking at Gradle's code (`AnnotationProcessorDetector`), it seems to be looking for manually configured `-processorpath` in the `compilerArgs` (which is what this plugin does), so compile avoidance should work.

> * Do you want me to me this question to a separate issue/question?

In case you'd have any more comment to make; then yes please (let's not pollute this issue too much and stop spamming others)

> * When we can change your plugin to use `annotationProcessorPath`?
> * Once this happens, I'd love to test it out on Android projects.

Not sure why you'd want to do that: aren't Android projects already have an `annotationProcessor` configuration? Also not sure why using Gradle 3.4+ `annotationProcessorPath` would be a prerequisite.
Please followup in a new issue, or by mail, for any further discussion.

**Comment by tbroyer** [comment]
@molexx I've split eclipse and idea into separate plugins in bb137dbc903bda432714b137454b3fcc8bc01fc2, so you can now apply `net.ltgt.apt` without it modifying the Eclipse or IDEA configuration.

**Comment by tbroyer** [comment]
Just published v0.11 with those changes; please test and report any regression, or any issue with the new behavior.

**Comment by tbroyer** [comment]
@molexx In v0.12, I added configuration switches (see README), so you could have the annotation processors added as dependencies but disable adding the generated sources directories (`idea.module.apt.addGeneratedSourcesDir=false`)

**Comment by molexx** [comment]
@tbroyer aha that looks great, thanks! Will have a play...
