### ISSUE TITLE
Path for Eclipse is generated improperly

### ISSUE THREAD

**Issue by eximius313** [tbroyer/gradle-apt-plugin#48]
We configured ```apt-plugin``` according to the documentation and ```./gradlew build``` run just fine.
Unfortunatelly when I execute ```./gradlew eclipse``` the source folder added to the classpath is being set to: ```build/generated/source``` which causes Eclipse to think, that ```apt.main.mypackage``` is a package. And that causes compilation errors because under ```apt/main/mypackage``` classes have package ```mypackage```, not ```apt.main.mypackage```
Setting source folder location manually to: ```build/generated/source/apt/main``` instad of ```build/generated/source``` solves the problem.

Can you please change it in your plugin?

**Comment by tbroyer** [comment]
I'd be happy to fix the plugin… **iff** it was responsible for that behavior. But the plugin specifically does **not** configure those paths (`build/generated/source/…`) in Eclipse due to how Eclipse is incapable of separating out main and test configurations; and configures the output of annotation processing to `.apt_generated` instead (where Eclipse will put all output from both main and test classes processing): https://github.com/tbroyer/gradle-apt-plugin/blob/v0.10/src/main/groovy/net/ltgt/gradle/apt/AptPlugin.groovy#L132

Do you have a small project available online that reproduces the problem? Could it be due to some other plugin you're using?

**Comment by eximius313** [comment]
Yes I have, but how can it help if you closed the issue as invalid?
On the other hand - you don't have to point src folder to ```main``` & ```test``` together. If you treat them separately - it works just fine (```build/generated/source/apt/main``` & ```build/generated/source/apt/test```) and should solve the issue

**Comment by tbroyer** [comment]
Sorry if I wasn't clear. I know the apt-gradle-plugin is not responsible for your Eclipse configuration; and I'm offering some help to help you diagnose it.

> On the other hand - you don't have to point src folder to `main` & `test` together. If you treat them separately - it works just fine (`build/generated/source/apt/main` & `build/generated/source/apt/test`) and should solve the issue

You're misunderstand the problem here.
In an Eclipse project there's no distinction between main and test classes, only one _build path_ for both, and only one output folder (that `./gradlew eclipse` configures as `bin/`); and when you configure annotation processing, there's only one _factory path_ and one output folder for the generated sources (which the apt-gradle-plugin configures as `.apt_generated/`).

FWIW, I just ran `./gradlew eclipse` on a small project and cannot find any mention of `build/generated/source` (or even `build/` for that matters) in the generated files (`.project`, `.classpath`, `.settings/org.eclipse.jdt.core.prefs`, `.factorypath`, and `.settings/org.eclipse.jdt.apt.core.prefs`). Tried with both Gradle 3.0 and 3.5, and apt-gradle-plugin 0.10.

**Comment by eximius313** [comment]
Ok, now I see the problem.
With the "plain" configuration we were not able to use generated classes in our code (I see that ```.apt_generated``` is being used in configuration but after ```./gradlew build``` it's empty. All classes are being generated to ```${buildDir}/generated/source```

That is why we needed to use:
```
sourceSets {
    main {
        java {
            srcDirs = ['src/main/java', "${buildDir}/generated/source"]
        }
        resources {
            srcDirs = ['src/main/resources', 'src/main/sql']
        }
    }
}
```
in our ```build.gradle``` file.
When I changed ```${buildDir}/generated/source``` to ```${buildDir}/generated/source/apt/main``` everything is working.

The question is - why ```.apt_generated``` is empty? Try it yourself (with and without ```sourceSets```) - my project is in attachment: [showcase.zip](https://github.com/tbroyer/gradle-apt-plugin/files/966075/showcase.zip)

**Comment by tbroyer** [comment]
`.apt_generated` is where Eclipse will write the generated sources, when it itself processes annotations. If you don't intend to use Eclipse's built-in support for annotation processing (and instead prefer to run Gradle to compile sources and write generated sources), then I suppose you're asking for a way to apply both `eclipse` and `net.ltgt.apt` plugins without the `net.ltgt.apt` plugin configuring Eclipse; similar to #45 for IntelliJ IDEA.

**Comment by ft0907** [comment]
I would like to ask how the STS used to customize the source code path. @tbroyer  @eximius313

**Comment by eximius313** [comment]
could you please be more specific? I'd like to help but I'm not sure what you need.

**Comment by ft0907** [comment]
A custom annotation processor is needed to generate the output path of the source code.But this is already a problem.
 Referring to this answer [https://github.com/gradle/gradle/issues/4956](url)

thank you very much for your answer.
