### ISSUE TITLE
apt-idea plugin causes 'apt' dependency to be added to as a 'compile' dependency

### ISSUE THREAD

**Issue by arminnaderi** [tbroyer/gradle-apt-plugin#61]
Proof in attached image. When I revert to just the apt plugin the compile dependency is gone. Any suggestions?
<img width="913" alt="screen shot 2017-10-07 at 1 26 10 am" src="https://user-images.githubusercontent.com/16402451/31305449-a0602230-aaff-11e7-9392-07ff823e3227.png">

**Comment by tbroyer** [comment]
Those are the dependencies *as seen by IntelliJ IDEA*, so that you can easily configure annotation processing by just telling IDEA to pick annotation processors from the classpath.

If you run `gradle dependencies`, you should see the annotation processors only in the `apt` configuration, **not** in the `compile` (or `compilClasspath`) one(s).

If you delegate IDEA build/run actions to Gradle, then you should set `idea.module.apt.addAptDependencies` to `false`, as explained in the README: https://github.com/tbroyer/gradle-apt-plugin#intellij-idea

**Comment by arminnaderi** [comment]
Hmm interesting `idea.module.apt.addAptDependencies` to `false` within the concerned module's build file solved the problem, but still not sure why this is the case. Perhaps I'll have to read into the Intellij architecture a bit more.

However, the `init.d` method did not work, both when placing it within the `.gradle` excluded directory of my Intellij project files and within the `gradle` directory. Any suggestions?

These are the two directories:
<img width="311" alt="screen shot 2017-10-07 at 7 55 45 pm" src="https://user-images.githubusercontent.com/16402451/31312976-912fede6-ab99-11e7-9177-a6e11064f795.png">

**Comment by tbroyer** [comment]
The init script is **system-wide**, it goes into your user home folder's `.gradle` (follow the link to the Gradle documentation from the README)
