### ISSUE TITLE
Intellij issues after version 0.10

### ISSUE THREAD

**Issue by tetv** [tbroyer/gradle-apt-plugin#65]
It seems that Intellij doesn't like versions 0.11 and 0.12.
With versions 0.09 and 0.10 no issues at all.

Tested on: Ubuntu, Intellij 2017.2.5, Gradle 4.2.1

**Comment by tbroyer** [comment]
I'm using IntelliJ IDEA 2017.2.5 and gradle-apt-plugin (various versions, though I try to migrate all my projects to Gradle 4.2.1 –or 4.3 when released– and gradle-apt-plugin 0.12) and do not have any problem.

Could you please give more details about what you're experiencing?

Could it just be that you didn't apply the `net.ltgt.apt-idea` plugin? That one is new in 0.11. See [the README](https://github.com/tbroyer/gradle-apt-plugin#intellij-idea) for details.

**Comment by tetv** [comment]
Basically I am using it with the [Immutable](https://immutables.github.io) library.

When I updated to v0.12 from v0.09 I didn't notice anything strange.
Days later after deleting the generated source folder in Intellij, I started having compilation issues.

After some tests in the gradle file with the version numbers followed by an reimport all gradle project, It was easy to conclude that. v0.09 and v0.10 was generating the *.java and *.class files, while the v0.11 and v0.12 not.

I checked in my .gradle/cache and all the versions were there, from v0.09 to v0.12.

Using the command line `gradle compileJava`, everything works fine regardless the version, and all the `*.class` files are generated. (The `*.java` aren't, which is fine.)

Note that I am using many projects in my `settings.gradle`, but only one has this plugin: 

```
plugins {
  id 'net.ltgt.apt' version '0.10' // 0.12 has issues with IntelliJ
}
```

**Comment by oopschen** [comment]
same issue with idea 2017.2.5, gradle 4.2, apt-plugin 0.12

**Comment by tbroyer** [comment]
So, I'll assume you're using the IntelliJ integration for importing your Gradle project into IntelliJ (vs. the `idea` task), and configure IntelliJ to do the annotation processing.

Using the `net.ltgt.apt-idea` plugin (either with the plugins DSL or `apply plugin`) should be enough then (and then go enable and configure annotation processing in IntelliJ settings).

BTW, a Gradle build **should** generate the Java sources into `build/generated/source/apt/…`; if that doesn't happen, then (unless your annotation processor directly generate bytecode, but that's not the case of Immutables) you have a problem.

> I recommend that you update the information of the plugin in two chapters:
> 
>  1. Basic/Minimum configuration (useful for probably the majority of the people)
>  2. Advanced configuration: All the details and depth of configurations

The problem is that the "basic/minimum" configuration itself varies greatly. I, for one, recommend using IntelliJ's integration along with `Delegate build/run actions to Gradle` (and I might very well make it “the default” in the next version; you currently need additional configuration in this setup). Others will prefer IntelliJ's integration without `Delegate build/run actions to Gradle` (or have an IntelliJ version that doesn't support it anyway), and then some of them will happily run Gradle to re-generate the sources whenever they make changes to their code that requires it, while others will want to have annotation processing done by IntelliJ. And finally, there will be those who prefer using the `idea` task (or have to use it for various reasons; e.g. Gradle itself). And a future version of IntelliJ might make use the Gradle 3.4's `compileJava.options.annotationProcessorPath` and Gradle 4.3's `compileJava.options.annotationProcessorGeneratedSourcesDirectory` to configure the IDE automatically, adding even more “basic” setup combinations.

I agree that a rework of the documentation might make it easier to comprehend, but I've done that several times already, and can't come up with something “satisfying”.

Also please note that IDE support is provided on a “best effort” basis.

That said, if you can share a project that reproduces the problem, I'll give it a look to try to understand what's happening.

**Comment by tetv** [comment]
Thanks @tbroyer for your effort.

My request is very *simple*. I would like to configure v0.12 to have the same behaviour as v0.10!

Saying that, what is the easy way to upgrade from v0.10 to v0.12 and maintain the same behaviour?

At the moment I am using it v0.10 without issues, however, let me see if I can create a simple project with this issue.

**Comment by tbroyer** [comment]
Applying the `net.ltgt.apt-idea` plugin _should_ get you the exact same behavior as in 0.10, without any other configuration.

**Comment by oopschen** [comment]
applying the **net.ltgt.apt-idea** do not work, no files generated at **build/generated/source/apt**
below is my gradle build.gradle file:
```
plugins {
    id 'org.springframework.boot' version '1.5.8.RELEASE'
    id 'io.franzbecker.gradle-lombok' version '1.10'
    id 'java'
    id "net.ltgt.apt" version "0.12"
    id "net.ltgt.apt-idea" version "0.12"
}


apply plugin: "net.ltgt.apt"
apply plugin: "net.ltgt.apt-idea"

jar {
    baseName = 'myproject'
    version = '0.0.1-SNAPSHOT'
}

repositories {
    jcenter()
}

configurations {
    compile.exclude module: "spring-boot-starter-tomcat"
    compile.exclude module: "spring-boot-starter-websocket"
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-redis
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-data-redis', version: '1.5.8.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-logging', version: '1.5.8.RELEASE'
    compile group: 'org.springframework.boot', name: 'spring-boot-starter-jetty', version: '1.5.8.RELEASE'
    compile("org.springframework.boot:spring-boot-devtools")
    // https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    compile group: 'org.apache.commons', name: 'commons-lang3', version: '3.6'


    testCompile("org.springframework.boot:spring-boot-starter-test")

    compileOnly 'org.immutables:value:2.5.5'
    apt 'org.immutables:value:2.5.5'
}
```

help me out, thx

**Comment by oopschen** [comment]
Finally, i figure out how to make it work. I am newbie in using the plugin.
`buildscript {
  repositories {
    maven {
      url "http://maven.aliyun.com/nexus/content/repositories/gradle-plugin/"
    }
  }
  dependencies {
    classpath "net.ltgt.gradle:gradle-apt-plugin:0.12"
  }
}

apply plugin: "net.ltgt.apt"
apply plugin: "net.ltgt.apt-idea"
apply plugin: 'java'


repositories {
  maven {
    url 'http://maven.aliyun.com/nexus/content/repositories/central/'
  }

  jcenter()
}

dependencies {
  compileOnly "com.google.auto.value:auto-value:1.5"
  apt         "com.google.auto.value:auto-value:1.5"
  testCompileOnly   "com.google.auto.value:auto-value:1.5"
  // https://mvnrepository.com/artifact/org.testng/testng
  testCompile group: 'org.testng', name: 'testng', version: '6.11'

}
`
this works, it generated java code at directory *build/generated/source/apt/* which is relative to my project root.
the normal steps is 

1. go to intellij, check the option *Enable annotation processing* at location: **File - Settings -  Build, Execution, ... - Compiler, Annotation Processors**
2. delegates the IDE  build/run actions to gradle
3. write a class using AutoSave
4. manually run the compile process

Then you will get the generated java file the location **build/generated/source/apt/**
