### ISSUE TITLE
A separate generateSources task to execute before compiling.

### ISSUE THREAD

**Issue by rolfw** [tbroyer/gradle-apt-plugin#71]
I [asked this related question on SO](https://stackoverflow.com/questions/47338146/gradleapt-a-generatesources-task-to-execute-before-compiling), but the apt-plugin would probably be the most appropriate place for this task. So here's a modified version of the question to request this feature;

------------------------------------------------------------------------------------

For several reasons I would like annotation processing to happen in separate tasks (one for each source set) and make the compile tasks depend on them. For example: `generateSources`, `generateTestSources`, `generateApiSources`, etc

## Rationale

I'm hoping to see a few benefits from generating and compiling as separate build stages;

#### Reduce secondary compiler errors
It would be nice if the build fails early during annotation processing, without reporting all the additional errors that come from regular sources that depend on generated classes that weren't generated because of a processor error. 

For instance: it often happens that [Dagger](https://github.com/google/dagger) fails because of an error in my code, which causes [Immutables](https://github.com/immutables/immutables) to not generate classes, which causes a whole bunch of irrelevant secondary errors to wade through. 

I'm hoping the compile task will never execute because generateSources has failed, which would limit the error output to the processor errors only. If not, I could still run the task separately to get the same benefits.

#### Formatting generated sources
I find it easier if code is consistently formatted when reading/debugging it, especially if it's not my own. I spend the majority of my time with my own code, but it does happen quite frequently in case of apparent problems with a processor (or my use thereof)

#### Apply license headers to generated sources
I consider generated sources part of the source too, so they should have license headers (whether open source or proprietary)

## Why not format / apply headers after compiling
Adding license headers and (often) formatting changes the line numbers of the source code, causing the `.class` files and the sources to diverge. I suspect it also gets in the way of incremental builds.

## Possible approach

I've added the following code to my build script to successfully generate sources only, but haven't been able to make a separate task of it yet.

```
    compileJava.doFirst {
	    if (project.hasProperty("procOnly")) {
    		options.compilerArgs << '-proc:only'
	    }
    }
```
Perhaps a simple approach could be duplicating each JavaCompile task, then configuring the regular compile tasks to use the `-proc:none` argument and the duplicated tasks (i.e. the generate tasks) to use the `-proc:only` argument.

**Comment by tbroyer** [comment]
I had once thought about it, but would rather see it as a separate plugin. Also, if you chain that with other tasks, those would possibly rather write the processed sources into distinct output folders (for incrementality; I'm not sure Gradle would like it if you had a downstream task overwrite the files in place), which means reconfiguring your compile tasks to take the processed generated sources as input. So it might actually not even be a good fit for a plugin.

Please experiment within your build script, then extract reusable snippets, and then we can think about turning them into a plugin (either here or a completely separate one). WDYT?

**Comment by rolfw** [comment]
That's a good point about changing files downstream. I'll park it for now, but will do some experimentation in the next couple of weeks. I'll let you know my findings.

**Comment by rolfw** [comment]
Did some experimentation already and when I add the code below to the build script it runs without errors when executing `gradle clean generateSources`:

```
task generateSources(type: JavaCompile) {

    doFirst {
        println "Compiler args: " + options.compilerArgs
    }

    // ====  Copy properties from corresponding compile task  =====
    classpath = sourceSets.main.compileClasspath
    destinationDir = compileJava.destinationDir
    excludes = compileJava.excludes
    includes = compileJava.includes
    source = compileJava.source
    sourceCompatibility = compileJava.sourceCompatibility
    targetCompatibility = compileJava.targetCompatibility
    toolChain = compileJava.toolChain

    // ====  Copy options  =====
    options.optionMap().clear()
    options.optionMap().putAll(compileJava.options.optionMap())

    // ====  Configure this compile task to process annotations only  =====
    options.compilerArgs << '-proc:only'

    // ====  Configure the main compile task to not process annotations at all  =====
    compileJava.options.compilerArgs << '-proc:none'
}

project.afterEvaluate {


    // ====  Ensure sources are generated before compiling  =====
    compileJava.dependsOn("generateSources")
}
```

However, it doesn't actually generate anything. The `println` that I added in the beginning prints this: `Compiler args: [-proc:only]`.

Do you see anything wrong with this?

**Comment by rolfw** [comment]
I noticed in method `configureCompileTasks` in `AptPlugin` that it sets generated sources directory and processor paths as compile options. But when I add the action below to the `generateSources` task to print the actual compiler options, the output is still `Compiler args: [-proc:only]`.

```
generateSources << {

    println "Compiler args: " + options.compilerArgs
}
```

Is there anything special I should do to make the apt plugin configure my `generateSources` task like it does for other `CompileJava` tasks? 

I'm trying to do it on my own, but I have no prior experience with gradle plugin development and only recently started using Gradle (and Groovy) at all, so I might overlook something obvious here.

**Comment by tbroyer** [comment]
The plugin only actually configures the `compilerArgs` in the task's `doFirst`, to resolve the configuration as late as possible, which means you'd have to actually execute the task to get the complete `compilerArgs`.
But this configuration comes from the `compileJava.aptOptions` extension, so you should be able to copy that instead.

Also, `optionsMap()` returns a new map each time, this is not a live view; so you need to use [`define()`](https://docs.gradle.org/4.3.1/javadoc/org/gradle/api/tasks/compile/AbstractOptions.html#define%28java.util.Map%29) to copy the options, instead of `clear()` & `putAll()` (this would also explain why you only have `-proc:only` in `compilerArgs`; because you didn't actually copy the options from `compileJava`)

**Comment by rolfw** [comment]
Thanks for these insights, with some more modifications it looks like I got it working. This is what I currently have:

```
task generateSources(type: JavaCompile) {

    // TODO: find a way to copy all options at once, including any extensions from other plugins such as AptOptions

    // ====  Copy properties from corresponding compile task  =====
    classpath = sourceSets.main.compileClasspath
    destinationDir = compileJava.destinationDir
    excludes = compileJava.excludes
    includes = compileJava.includes
    source = compileJava.source
    sourceCompatibility = compileJava.sourceCompatibility
    targetCompatibility = compileJava.targetCompatibility
    toolChain = compileJava.toolChain

    // ====  Copy compile options  =====
    /* NOTE: AbstractOptions.define(Map<String, Object>) doesn't seem to work so we set each property manually for now */
    options.annotationProcessorPath = compileJava.options.annotationProcessorPath
    options.bootClasspath = compileJava.options.bootClasspath
    options.compilerArgs = compileJava.options.compilerArgs
    options.debug = compileJava.options.debug
    options.debugOptions = compileJava.options.debugOptions
    options.deprecation = compileJava.options.deprecation
    options.encoding = compileJava.options.encoding
    options.extensionDirs = compileJava.options.extensionDirs
    options.failOnError = compileJava.options.failOnError
    options.fork = compileJava.options.fork
    options.forkOptions = compileJava.options.forkOptions
    options.incremental = compileJava.options.incremental
    options.sourcepath = compileJava.options.sourcepath
    options.verbose = compileJava.options.verbose
    options.warnings = compileJava.options.warnings

    // ====  Copy apt options (from gradle-apt-plugin)  =====
    aptOptions.annotationProcessing = compileJava.aptOptions.annotationProcessing
    aptOptions.processorpath = compileJava.aptOptions.processorpath
    aptOptions.processors = compileJava.aptOptions.processors
    aptOptions.processorArgs = compileJava.aptOptions.processorArgs

    // ====  Configure this task to output in proper directory  =====
    // TODO: is this the proper way to do it?
    // TODO: replace hard-coded path
    def generatedSourcesDir = file(new File(buildDir, "/generated/source/apt/main"))
    doFirst {
        generatedSourcesDir.mkdirs()
    }
    options.compilerArgs << "-s"
    options.compilerArgs << generatedSourcesDir

    // ====  Configure this compile task to process annotations only  =====
    options.compilerArgs << '-proc:only'

    doLast {

        // ====  Configure the main compile task to include the generated sources  =====
        // TODO: is this the proper way to do it?
        compileJava.options.sourcepath = files(generatedSourcesDir)

        // ====  Configure the main compile task to not process annotations at all  =====
        compileJava.options.compilerArgs.remove '-proc:only'
        compileJava.options.compilerArgs.add '-proc:none'
    }
}

project.afterEvaluate {

    // ====  Ensure sources are generated before compiling  =====
    compileJava.dependsOn("generateSources")
}
```

The `define` method didn't work for me because of this (seemingly unrelated) error: `Could not find setter method for property 'nowarn' of type Boolean on class CompileOptions.`

When I replaced `options.define(compileJava.options.optionMap())` with `options.define(null)` the error goes away, but it obviously doesn't copy any options then. I noticed the define method [isn't documented](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html) but I can see that the `define(@Nullable Map<String, Object>)` method exists. Perhaps it's a bug. I got it working for now by manually copying each property though.

I'll rewrite this as a task type (e.g. `JavaGenerateSources`) that properly configures each `JavaCompile` task, creates a corresponding `JavaGenerateSources` task and uses proper task inputs and outputs for incremental compilation & inferring dependencies between tasks from other plugins.

Are you interesting in a pull request to add this to your apt plugin? If so, do you have any specific guidelines? And do you mind answering a few questions here and there? 

I'm not quite sure how to best approach the issues marked with `// TODO: `, for instance :)

**Comment by tbroyer** [comment]
wrt. `generatedSourcesDir`, the following should work:
```gradle
generatedSourcesDestinationDir = compileJava.generatedSourcesDestinationDir
```
(another extension from this plugin), and then you won't need the `mkdirs()`.
You'll probably want to then `null` out the `compileJava.generatedSourcesDestinationDir` to make sure it's not taken into account for the up-to-date checks.

wrt. the `compileJava` configuration, you'll probably actually want to add the `generatedSources` output as a source:
```gradle
compileJava.source generatedSources
```
(and this will automatically configure the task dependency, so no need for `dependsOn`).
You'll probably want to use separate `destinationDir` for both tasks too, because annotation processors can generate things –e.g. resources– in the `destinationDir`; you'll probably want to add that `destinationDir` as a resources dir (don't forget the `builtBy` for proper task ordering). This is why I directly used the task above; otherwise, if they share the same output directory, incremental build won't work (the folder will be snapshoted after `generateSources` execution, so next time the task would have to re-run because the `compileJava` task will have added new output; fwiw, this is the reason Gradle 4.3 now uses separate output folders for compile tasks –for Java vs. Groovy vs. etc.–, to make it easier to manage).

This can quickly get very hairy if you want to support all use cases.

> Are you interesting in a pull request to add this to your apt plugin?

The more I think about it, the more I want to say no (and I'll close the issue as a signal). This is not code that I'm willing to eventually maintain. I strongly believe you should experiment with snippets in various projects, refine the snippets, then only possibly package the logic as a plugin. Fwiw, you can easily share snippets between projects using `apply from:`. This is actually how I started the gradle-errorprone-plugin: https://gist.github.com/tbroyer/6847494

**Comment by rolfw** [comment]
Having spent more time on this, I can see how this gets hairy, and why you're probably not keen on maintaining it. I'll experiment over time as you suggest and might publish a plugin at some point, depending on my experience and how Gradle's APT support evolves over time.

In any case thanks for your help and your last suggestions. I've implemented all of them except builtBy (destinationDir is a File and doesn't have that property). But I'm moving on with other stuff so I'm setting dependencies manually for the time being.

I'll clean up my code a bit, test it a bit more and then post it here for anyone interested.

**Comment by rolfw** [comment]
Actually, I have two more questions if you don't mind;

> You'll probably want to use separate destinationDir for both tasks too, because annotation processors can generate things –e.g. resources– in the destinationDir; you'll probably want to add that destinationDir as a resources dir (don't forget the builtBy for proper task ordering).

I changed the destinationDir for the generate sources task to `build/generated/resource/apt/${sourceSet}`, but I couldn't find any property on the compile task to set to this new resources dir. So I'm currently getting the sourceset (using the task's name) and add the directory to the resources: `sourceSet.resources.srcDirs += generateSourcesTask.generatedResourcesDir`

But this causes other tasks such as those from hierynomus/license-gradle-plugin to change the generated files, messing up incremental builds. Where should I set the resources dir instead?
 
> wrt. the compileJava configuration, you'll probably actually want to add the generatedSources output as a source: `compileJava.source generatedSources`
> (and this will automatically configure the task dependency, so no need for dependsOn)

I'm currently doing it like this and it works fine:

```
compileTask.configure {
			if (source == null) {
				source = generateSourcesTask.generatedSourcesDir
			} else {
				source = project.files(source, generateSourcesTask.generatedSourcesDir)
			}
		}
}
```
But Gradle doesn't infer a dependency from the compile task on the generate sources task. Not a big deal because I'm now adding them explicitly, but it makes me wonder if this causes other problems too. Do you see anything wrong with this?

**Comment by tbroyer** [comment]
> but I couldn't find any property on the compile task to set to this new resources dir.

Resources are processed by the `processResources` task (a simple `Copy` task to `sourceSets.main.output.resourcesDir`; see https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_tasks), the Java compiler only cares about `*.java` files (annotation processors might use resources, but we're past that step already).

> But this causes other tasks such as those from hierynomus/license-gradle-plugin to change the generated files, messing up incremental builds.

If you're gonna use `licenseFormat` during your build, this will necessarily mess up incrementality, because the plugin changes sources in place, so it invalidates things that generated them. The plugin would have to let you write formatted files in a distinct output folder to make incremental builds possible. Or you could possibly start playing with the `generateSources` task's [`outputs.upToDateWhen`](https://docs.gradle.org/4.3.1/javadoc/org/gradle/api/tasks/TaskOutputs.html#upToDateWhen%28org.gradle.api.specs.Spec%29) to have it skipped when needed. Or maybe just copy the outputs to another folder (**not** declared as a task's output dir) in `onLast`, that you use as inputs to `licenseFormat`.

> But Gradle doesn't infer a dependency from the compile task on the generate sources task.

That's because `generatedSourcesDir` is just a `java.io.File` with no information of where it comes from. You have to use `files(generatedSources.generatedSourcesDir) { builtBy generatedSources }` to create a `FileCollection` that links back to the task. But as I said above, if you use the task itself, it will use all its outputs (`generatedSourcesDir` and `destinationDir`) and infer the task dependency at the same time.
Also, use the [`source()` method](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html#org.gradle.api.tasks.compile.JavaCompile:source%28java.lang.Object[]%29) to *add* sources, don't assign the [`source` property](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.JavaCompile.html#org.gradle.api.tasks.compile.JavaCompile:source) as that *replaces* existing sources (setup by the `java` plugin to the `sourceSets.main.java` `FileTree`) and requires you to use that `if…else` construction.

**Comment by rolfw** [comment]
> Or you could possibly start playing with the generateSources task's outputs.upToDateWhen to have it skipped when needed

Is it safe to assume that generateSources is up-to-date if it's inputs are up-to-date? If so, how can I determine that? There doesn't seem to be a property for that on [TaskInputs](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/TaskInputs.html).

> That's because generatedSourcesDir is just a java.io.File with no information of where it comes from. You have to use files(generatedSources.generatedSourcesDir) { builtBy generatedSources } to create a FileCollection that links back to the task. But as I said above, if you use the task itself, it will use all its outputs (generatedSourcesDir and destinationDir) and infer the task dependency at the same time.

Got it. It works when I use that method and add the FileCollection as suggested. What do you mean with "if you use the task itself..." though?

**Comment by tbroyer** [comment]
> Is it safe to assume that generateSources is up-to-date if it's inputs are up-to-date?

Well, no (otherwise Gradle would do just that ;-) )
It could be "enough", but it's not "safe" (e.g. if you delete an output file or the output directory, you then wouldn't detect it and wouldn't re-run the task)

> If so, how can I determine that? There doesn't seem to be a property for that on TaskInputs.

Actually, `upToDateWhen` wouldn't even allow you to bypass the check: https://discuss.gradle.org/t/outputs-uptodatewhen-confusion/17973/3

So copying files looks like the only solution.

> What do you mean with "if you use the task itself..." though?

```gradle
compileJava.source generatedSources
```
(where `compileJava` and `generatedSources` are tasks)
See https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_output_side_effects

**Comment by rolfw** [comment]
> Actually, upToDateWhen wouldn't even allow you to bypass the check: https://discuss.gradle.org/t/outputs-uptodatewhen-confusion/17973/3

Hairy indeed :) But wouldn't any solution that involves copying either: A) leave (a copy of) generated sources without headers, or B) get in the way of incremental compilation?
