### ISSUE TITLE
Setting an out-of-source buildDir breaks IntelliJ apt build

### ISSUE THREAD

**Issue by shoreadmin** [tbroyer/gradle-apt-plugin#72]
We're currently experimenting using an out-of-source build dir.  From [this comment](https://discuss.gradle.org/t/does-gradle-support-out-of-source-builds/4148/2) it looks like it should be supported and does work for us using the command line gradle build.

The apt plugin fails with IntelliJ 2017.1 and 2017.2, however.  We're using gradle 4.3.

Given the default settings as described in the apt-plugin README, if the buildDir is set to "C:/temp" for example, the module content roots are added to the IntelliJ project (ie. "c:/temp/generated/source/apt/main" and "c:/temp/generated/source/apt/test"), however the generated files seem to be placed relative to the first module content root (ie "c:/temp/generated/source/apt/main").  eg. "c:/temp/generated/source/apt/main/build/generated/source/apt/[main|test]/...".

To make matters more complicated, it looks like IntelliJ has started to intentionally separate it's output directory from the standard gradle output directory (see https://youtrack.jetbrains.com/issue/IDEA-175172)...

**Comment by tbroyer** [comment]
I'm afraid this is purely an IntelliJ IDEA configuration issue, as all the plugin does in this case is to add the annotation processor dependencies to the project so you can easily get them by checking `Obtain processors from project classpath` in IDEA's annotation processing settings (and configure the output folders as generated source roots, but you're talking about where IDEA puts the generated files here, not where it looks them up, right?)

Please also note that IDE support is provided as a "best effort", and can be disabled since version 0.12 (by setting `idea.module.apt.addGeneratedSourcesDirs` and/or `idea.module.apt.addAptDependencies` to `false`); and I strongly recommend configuring IntelliJ IDEA to delegate build/run actions to Gradle to avoid those kinds of problems (the IDE behaving differently from the actual build tool).

**Comment by shoreadmin** [comment]
We prefer to use IntelliJ's build system as it is much faster than the gradle build (although we do use the gradle build during CI).  Ignoring issues with out-of-source builds, the two build systems have worked quite well together in the past, although the IntelliJ youtrack issue I mentioned earlier would suggest that they might deviate further in the future.  While it would be nice to be able to just import a gradle project and be able to configure the IDE to "just work" - I understand that this may not always be possible...

In any case, I think the underlying issue in this case is that IntelliJ's annotation processor setting `Store generated sources relative to Module content root` doesn't take into account the fact that there may be multiple content roots.  The source files are generated in a directory that is relative to the first content root in the list - and it appears that this list is sorted alphabetically!!  So we have bigger problems anyway - I might raise a ticket with JetBrains...

**Comment by shoreadmin** [comment]
Raised https://youtrack.jetbrains.com/issue/IDEA-183214
