### ISSUE TITLE
Missing copyright information

### ISSUE THREAD

**Issue by kravemir** [tbroyer/gradle-apt-plugin#89]
The project is missing copyright information, ie. who is copyright holder. Debian packaging requires copyright and license for package, specifically following: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#files-paragraph

I have tried searching also on maven repository, there's no information about copyright holder: https://mvnrepository.com/artifact/net.ltgt.gradle/gradle-apt-plugin/0.18

Can you please add that information?

**Comment by kravemir** [comment]
Great, thank you!

Did you think about getting this plugin packaged for most popular Linux distributions? Or, at least, would you like to have the plugin packaged for most popular Linux distributions?

**Comment by tbroyer** [comment]
This is beyond me why one would ever want to do that. As I understand it, this is a requirement for building Debian packages that all dependencies, even those needed only at build time, be packaged as well; but why would anyone want to use a package when the build tool is designed to download dependencies from remote repos (in this case, the Gradle Plugin Portal) automatically, keeping them in a cache locally, shared by all builds by the same user on the machine, and easily allowing many versions of such dependencies to coexist?

**Comment by kravemir** [comment]
> This is beyond me why one would ever want to do that. As I understand it, this is a requirement for building Debian packages that all dependencies, even those needed only at build time, be packaged as well;

This is true. And, also true for Fedora. Didn't check others.

>  but why would anyone want to use a package when the build tool is designed to download dependencies from remote repos (in this case, the Gradle Plugin Portal) automatically,

Because, somebody would like to get his/her work packaged, especially if it's an application, or CLI-tool. Without having dependencies packaged first, the tool/application won't get packaged. And, that would mean, much more complicated distribution to end users.

> keeping them in a cache locally, shared by all builds by the same user on the machine, and easily allowing many versions of such dependencies to coexist?

Well, major version should be backwards compatible. And, I saw debian java packages duplicated for each major version: https://packages.debian.org/search?suite=sid&searchon=names&keywords=jexl

**Comment by tbroyer** [comment]
> Because, somebody would like to get his/her work packaged, especially if it's an application, or CLI-tool. Without having dependencies packaged first, the tool/application won't get packaged. And, that would mean, much more complicated distribution to end users.

I'm afraid this is a concern for packagers (and/or application authors), not me.
I'm saying this without any animosity.
You're asking me whether I'd “like to have the plugin packaged for most popular Linux distributions”, and I don't care, in all honesty. Most users won't use it that way; I'd posit that the **only** users are the packagers of applications that use it in their build (including those people who prefer building everything from source).
I'm OK to make some (easy) changes to make their lives easier, because I have no reason not to (I do support open source and free software, I'm a Linux user after all), but did I think about having this packaged for a Linux distro? Not even for a split second. Would I like to have it package? I don't care, do as you want/need; ask for changes if you need them, I'll support you; but I don't care :man_shrugging: 

> Well, major version should be backwards compatible.

Please note that this plugin is 0.x and doesn't _guarantee_ backwards compatibility (and this is on purpose; the goal is that it eventually won't be needed anymore). It does however have a good compatibility track.

---

AIUI, you're going to patch build files (make all builds compatible with the version of Gradle packaged for Debian –rather than using the Gradle Wrapper–, which could mean updating plugins –assuming it is possible, you're (Debian) forcing yourself into a dependency mess– et al.)
If you're going to patch files, and you use a recent-enough version of Gradle (4.6+), then you could just as well patch this plugin out entirely (see https://github.com/tbroyer/gradle-apt-plugin/issues/80#issuecomment-388324203 and https://github.com/gradle/gradle/issues/2300#issuecomment-396858012)
